services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    build: ./jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sme-network

  db-postgres:
    image: ankane/pgvector:latest
    container_name: sme-postgres
    environment:
      POSTGRES_DB: sme_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistence for loan data
    networks:
      - sme-network

  redis:
    image: redis:alpine
    container_name: sme-redis
    networks:
      - sme-network

  minio:
    image: minio/minio
    container_name: sme-minio
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data # Persistence for KYC documents
    networks:
      - sme-network

  sonarqube:
    image: sonarqube:lts-community
    container_name: sme-sonarqube
    ports:
      - "9000:9000"
    networks:
      - sme-network
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  mailpit:
    image: axllent/mailpit
    container_name: sme-mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP Port
    networks:
      - sme-network

networks:
  sme-network:
    driver: bridge

volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgres_data: # New volume
  minio_data:    # New volume