pipeline {
    agent any

    environment {
        APP_NAME = 'sme-backend'
        IMAGE_NAME = 'sme-fastapi-prod'
        DB_URL = credentials('sme-db-url')
        GIT_CREDS_ID = 'my-git-creds'
        MAIL_HOST = 'mailpit'
        BUILDX_BUILDER = 'sme-builder'
        REPO_URL = 'https://github.com/Shubrajit22/BharatSME.git'
    }

    stages {
        stage('Fetch Source') {
            steps {
                script {
                    def scmInfo = git branch: "${BRANCH_NAME}",
                        credentialsId: "${GIT_CREDS_ID}",
                        url: "${REPO_URL}"
                    env.GIT_COMMIT_SHORT = scmInfo.GIT_COMMIT.take(7)
                }
            }
        }

        stage('Build Image (Buildx)') {
            steps {
                script {
                    // Check if 'sme-builder' already exists
                    def builderExists = sh(
                        script: "docker buildx ls | grep sme-builder", 
                        returnStatus: true
                    ) == 0

                    if (!builderExists) {
                        echo "Creating new buildx builder: sme-builder"
                        sh "docker buildx create --name sme-builder --use"
                    } else {
                        echo "Using existing buildx builder: sme-builder"
                        sh "docker buildx use sme-builder"
                    }

                    sh "docker buildx build --platform linux/amd64 --load -t sme-fastapi-prod:${env.BUILD_NUMBER} -t sme-fastapi-prod:latest ."
                }
            }
        }

        stage('SAST Analysis (SonarQube)') {
            steps {
                withSonarQubeEnv('SonarQubeServer') {
                    sh """
                        docker run --rm \
                        --network bharatsme_sme-network \
                        -v ${WORKSPACE}/backend:/usr/src \
                        sonarsource/sonar-scanner-cli \
                        -Dsonar.projectKey=sme-loan-backend \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=${SONAR_HOST_URL} \
                        -Dsonar.login=${SONAR_AUTH_TOKEN}
                    """
                }
            }
        }

        stage('Unit Tests') {
            agent {
                docker { image 'python:3.10-slim' }
            }
            steps {
                sh 'pip install -r backend/requirements.txt'
                sh 'pytest backend/tests --junitxml=results.xml'
            }
        }

        stage('Deploy Backend') {
            steps {
                script {
                    sh "docker ps -aq --filter name=${APP_NAME} | xargs -r docker rm -f"
                   sh """
                    docker run -d \
                    --name ${APP_NAME} \
                    --network sme_sme-network \
                    -p 8000:8000 \
                    -e DATABASE_URL=${DB_URL} \
                    -e MAIL_SERVER=mailpit \
                    -e MAIL_PORT=1025 \
                    -e SMTP_USERNAME=no-reply@bharatsme.in \
                    -e SMTP_PASSWORD=testing \
                    ${IMAGE_NAME}:latest
                    """
                }
            }
        }

        stage('Generate Build Documentation') {
            steps {
                script {
                    def date = sh(script: 'date "+%Y-%m-%d %H:%M:%S"', returnStdout: true).trim()
                    def report = """
                            # SME Project Session Report: Build #${BUILD_NUMBER}
                            **Date:** ${date}
                            **Branch:** `${BRANCH_NAME}`
                            **Commit:** `${env.GIT_COMMIT_SHORT}`

                            ---

                            ### 🚀 Deployment Summary
                            - **Service Name:** `${APP_NAME}`
                            - **Image:** `${IMAGE_NAME}:${BUILD_NUMBER}`
                            - **Status:** ✅ Successfully Deployed to Local Docker

                            ### 🔍 Quality & Security
                            - **SonarQube Analysis:** [View Dashboard](http://localhost:9000/dashboard?id=sme-loan-backend)
                            - **SAST Check:** Passed
                            - **Unit Tests:** Completed (See archived `results.xml`)

                            ### 🛠️ Infrastructure Environment
                            - **Database:** PostgreSQL (pgvector)
                            - **Object Storage:** MinIO
                            - **Mailing Interface:** Mailpit (Port 8025)
                            - **Cache Driver:** Redis

                            ---
                            *Generated by Jenkins Automation*
                            """
                    writeFile file: 'SESSION_REPORT.md', text: report
                    archiveArtifacts artifacts: 'SESSION_REPORT.md, results.xml'
                }
            }
        }

        stage('Maintenance & Pruning') {
            steps {
                script {
                    sh 'docker system prune -f --filter "until=24h"'
                    sh "docker buildx prune --builder ${BUILDX_BUILDER} -f"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}